apiVersion: v1
kind: Service
metadata:
  name: webapp-service
  namespace: icgroup
  labels:
    env: prod
spec:
  type: NodePort
  selector:
    app: ic-webapp
  ports:
    - port: 80
      targetPort: 8080
      nodePort: 30001
